steps:
  - name: Clone Repo
    image: alpine/git:latest
    commands:
      - git clone https://github.com/thevoid12/hello-go.git /workspace/hello-go

  - name: Build and Deploy with Docker Compose
    image: docker/compose:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/void/hello-go:/workspace/hello-go
    commands:
      - docker-compose -f /workspace/hello-go/docker-compose.yml up -d --build

when:
  branch: main
  event: push


