
services:
  hello-go:
    build: .
    container_name: hello-go-app
    ports:
      - "8080:8080"
    networks:
      - infra-net

networks:
  infra-net:
    external: true    # tells Docker not to create a new network but to attach to the existing one made by the infra stack.